INSERT INTO tbl_selecoes VALUES(null, "Rússia", "A", 0);
INSERT INTO tbl_selecoes VALUES(null, "Brasil", "E", 0);
INSERT INTO tbl_selecoes VALUES(null, "Irã", "B", 0);
INSERT INTO tbl_selecoes VALUES(null, "Japão", "H", 0);
INSERT INTO tbl_selecoes VALUES(null, "México", "F", 0);
INSERT INTO tbl_selecoes VALUES(null, "Bélgica", "G", 0);
INSERT INTO tbl_selecoes VALUES(null, "Coreia do Sul", "F", 0);
INSERT INTO tbl_selecoes VALUES(null, "Arábia Saudita", "A", 0);
INSERT INTO tbl_selecoes VALUES(null, "Alemanha", "F", 0);
INSERT INTO tbl_selecoes VALUES(null, "Inglaterra", "G", 0);
INSERT INTO tbl_selecoes VALUES(null, "Espanha", "B", 0);
INSERT INTO tbl_selecoes VALUES(null, "Nigéria", "D", 0);
INSERT INTO tbl_selecoes VALUES(null, "Costa Rica", "E", 0);
INSERT INTO tbl_selecoes VALUES(null, "Polônia", "H", 0);
INSERT INTO tbl_selecoes VALUES(null, "Egito", "A", 0);
INSERT INTO tbl_selecoes VALUES(null, "Islândia", "D", 0);
INSERT INTO tbl_selecoes VALUES(null, "Sérvia", "E", 0);
INSERT INTO tbl_selecoes VALUES(null, "França", "C", 0);
INSERT INTO tbl_selecoes VALUES(null, "Portugal", "B", 0);
INSERT INTO tbl_selecoes VALUES(null, "Argentina", "D", 0);
INSERT INTO tbl_selecoes VALUES(null, "Colômbia", "H", 0);
INSERT INTO tbl_selecoes VALUES(null, "Uruguai", "A", 0);
INSERT INTO tbl_selecoes VALUES(null, "Panamá", "G", 0);
INSERT INTO tbl_selecoes VALUES(null, "Senegal", "H", 0);
INSERT INTO tbl_selecoes VALUES(null, "Marrocos", "B", 0);
INSERT INTO tbl_selecoes VALUES(null, "Tunísia", "G", 0);
INSERT INTO tbl_selecoes VALUES(null, "Suíça", "E", 0);
INSERT INTO tbl_selecoes VALUES(null, "Croácia", "D", 0);
INSERT INTO tbl_selecoes VALUES(null, "Suécia", "F", 0);
INSERT INTO tbl_selecoes VALUES(null, "Dinamarca", "C", 0);
INSERT INTO tbl_selecoes VALUES(null, "Austrália", "C", 0);
INSERT INTO tbl_selecoes VALUES(null, "Peru", "C", 0);

